version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "20000:20000"
    volumes:
      - ./backend:/app
      - ./backend/requirements.txt:/app/requirements.txt
    # Optionally, set environment variables or command overrides for dev

  frontend:
    build: ./frontend
    ports:
      - "30000:30000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    # Optionally, set environment variables or command overrides for dev